name: ekipman_pc
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  cloud_firestore: ^2.1.0
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.9
  fl_chart: ^0.36.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/kasa.png
    - assets/images/ekrankartt.jpg
    - assets/images/rtx.jpg
    - assets/images/msi.jpg
    - assets/images/steelseries.jpg
    - assets/images/rtx3090.jpg
    - assets/images/5500xt.jpg
    - assets/images/rx580.jpg
    - assets/images/msimonitor.jpg
    - assets/images/asus.jpg
    - assets/images/razer.jpg
    - assets/images/hyperx.jpg
    - assets/images/medusa.jpg
    - assets/images/corsairkapak2.jpg
    - assets/images/corsair1.jpg
    - assets/images/corsair2.jpg
    - assets/images/corsair3.jpg
    - assets/images/hyperx1.jpg
    - assets/images/hyperx2.jpg
    - assets/images/hyperx3.jpg
    - assets/images/logig502.jpg
    - assets/images/logig5021.jpg
    - assets/images/logig5022.jpg
    - assets/images/logig5023.png
    - assets/images/medusa1.jpg
    - assets/images/medusa2.jpeg
    - assets/images/medusa3.jpg
    - assets/images/monsterpusat.jpg
    - assets/images/monsterpusat1.jpg
    - assets/images/monsterpusat2.jpg
    - assets/images/monsterpusat3.jpg
    - assets/images/tforcedeltakapak.jpg
    - assets/images/tforcedeltaram1.jpg
    - assets/images/tforcedeltaram2.jpeg
    - assets/images/tforcedeltaram3.jpg
    - assets/images/gamepowermedusaappbar.jpeg
    - assets/images/graffik.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DelaGothicOne
      fonts:
        - asset: assets/fonts/DelaGothicOne-Regular.ttf

    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf

    - family: BlackOpsOne
      fonts:
        - asset: assets/fonts/BlackOpsOne-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
